### ISSUE TITLE
Update gas limit to 36M instead, due to security concerns

### ISSUE THREAD

**Issue by yawarasuuna** [nanexcool/pumpthegas#6]
As discussed [here](https://ethresear.ch/t/on-increasing-the-block-gas-limit-technical-considerations-path-forward/21225), [here](https://xcancel.com/potuz_eth/status/1865880968935932124), and [here ](https://xcancel.com/drakefjustin/status/1866021455437476270), due to security concerns, a 60 million gas limit might not be prudent , and right now it could lead to a full liveness attack on the network until this issue is fixed. All client devs are already working on a fix to it.

Instead, we could safely increase the gas limit to 36 million, a 20% increase, at least until Pectra goes live and further data is available to be analyzed.

**Comment by prestonvanloon** [comment]
Please see ACD 147 https://github.com/ethereum/pm/issues/1211

The network gossip limits will not be raised until Pectra. Advertising 60M is a risk until after Pectra.

**Comment by nanexcool** [comment]
Yup, we're gonna suggest 36M as well, thanks for the PR!
